remote_theme: just-the-docs/just-the-docs
color_scheme: dark
title: Learning Log
description: Notepad
baseurl: "/"
url: "https://csk200387.github.io"
aux_links:
  "GitHub":
    - "//github.com/csk200387"


# Footer "Edit this page on GitHub" link text
gh_edit_link: true # show or hide edit this page link
gh_edit_link_text: "GitHub"
gh_edit_repository: "https://github.com/csk200387/csk200387.github.io"

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# Google Analytics Tracking (optional)
# Supports a CSV of tracking ID strings (eg. "UA-1234567-89,G-1AB234CDE5")
ga_tracking: UA-1234567-89, G-1AB234CDE5
ga_tracking_anonymize_ip: true # Use GDPR compliant Google Analytics settings (true/nil by default)